// <auto-generated />
using System;
using Kalon.Back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kalon.Back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424210608_SendingPreferences to Organization")]
    partial class SendingPreferencestoOrganization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kalon.Back.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsOut")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PreferredFrequencySendingReceipt")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Department");

                    b.HasIndex("OrganizationId", "Kind");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.ContactStatusSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InactiveAfterMonths")
                        .HasColumnType("integer");

                    b.Property<int>("NewDurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToRemindAfterMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("contact_status_settings", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.ContentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoredPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UsableInEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("UsableInReceipt")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Kind");

                    b.ToTable("content_blocks", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GeneratedDocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("GeneratedDocumentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Date");

                    b.HasIndex("OrganizationId", "DonationType");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailTemplateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.GeneratedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<string>("SendError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentToEmail")
                        .HasColumnType("text");

                    b.Property<string>("SignatureImagePath")
                        .HasColumnType("text");

                    b.Property<decimal>("SnapshotAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SnapshotContactAddress")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotContactDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnapshotContactSiret")
                        .HasColumnType("text");

                    b.Property<DateTime>("SnapshotDonationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SnapshotDonationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnapshotOrgCity")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotOrgFiscalStatus")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotOrgName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnapshotOrgPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotOrgRna")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotOrgSiret")
                        .HasColumnType("text");

                    b.Property<string>("SnapshotOrgStreet")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TaxReductionRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "DocumentType");

                    b.HasIndex("OrganizationId", "OrderNumber");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("generated_documents", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.MailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("GeneratedDocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEmail")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MailedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PrintedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentToEmail")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("GeneratedDocumentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("mail_logs", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivitySector")
                        .HasColumnType("text");

                    b.Property<string>("AudienceDescription")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultReceiptFrequency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FiscalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("RNA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SIRET")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .HasColumnType("text");

                    b.Property<string>("SendingPreferences")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.OrganizationLogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("organization_logos", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssociationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MeranId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MeranId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kalon.Back.Models.Contact", b =>
                {
                    b.HasOne("Kalon.Back.Models.Organization", "Organization")
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Kalon.Back.Models.ContactAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_country");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("address_email");

                            b1.Property<string>("Phone")
                                .HasColumnType("text")
                                .HasColumnName("address_phone");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.HasKey("ContactId");

                            b1.ToTable("contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("Kalon.Back.Models.ContactEnterprise", "Enterprise", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_city");

                            b1.Property<string>("ContactEmail")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_contact_email");

                            b1.Property<string>("ContactFirstname")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_contact_firstname");

                            b1.Property<string>("ContactLastname")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_contact_lastname");

                            b1.Property<string>("ContactPhone")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_contact_phone");

                            b1.Property<string>("Country")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_country");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("enterprise_name");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_postal_code");

                            b1.Property<string>("Siret")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_siret");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_street");

                            b1.Property<string>("SupportKind")
                                .HasColumnType("text")
                                .HasColumnName("enterprise_support_kind");

                            b1.HasKey("ContactId");

                            b1.ToTable("contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Enterprise");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kalon.Back.Models.ContactStatusSettings", b =>
                {
                    b.HasOne("Kalon.Back.Models.Organization", "Organization")
                        .WithOne("ContactStatusSettings")
                        .HasForeignKey("Kalon.Back.Models.ContactStatusSettings", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kalon.Back.Models.ContentBlock", b =>
                {
                    b.HasOne("Kalon.Back.Models.Organization", "Organization")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kalon.Back.Models.Donation", b =>
                {
                    b.HasOne("Kalon.Back.Models.Contact", "Contact")
                        .WithMany("Donations")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalon.Back.Models.GeneratedDocument", "GeneratedDocument")
                        .WithMany("Donations")
                        .HasForeignKey("GeneratedDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kalon.Back.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("GeneratedDocument");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kalon.Back.Models.EmailTemplate", b =>
                {
                    b.HasOne("Kalon.Back.Models.Organization", "Organization")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kalon.Back.Models.GeneratedDocument", b =>
                {
                    b.HasOne("Kalon.Back.Models.Organization", "Organization")
                        .WithMany("GeneratedDocuments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kalon.Back.Models.MailLog", b =>
                {
                    b.HasOne("Kalon.Back.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalon.Back.Models.GeneratedDocument", "GeneratedDocument")
                        .WithMany()
                        .HasForeignKey("GeneratedDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kalon.Back.Models.Organization", "Organization")
                        .WithMany("MailLogs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("GeneratedDocument");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kalon.Back.Models.Organization", b =>
                {
                    b.HasOne("Kalon.Back.Models.User", "User")
                        .WithOne("Organization")
                        .HasForeignKey("Kalon.Back.Models.Organization", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kalon.Back.Models.OrganizationLogo", b =>
                {
                    b.HasOne("Kalon.Back.Models.Organization", "Organization")
                        .WithOne("Logo")
                        .HasForeignKey("Kalon.Back.Models.OrganizationLogo", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Kalon.Back.Models.Contact", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("Kalon.Back.Models.GeneratedDocument", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("Kalon.Back.Models.Organization", b =>
                {
                    b.Navigation("ContactStatusSettings");

                    b.Navigation("Contacts");

                    b.Navigation("ContentBlocks");

                    b.Navigation("EmailTemplates");

                    b.Navigation("GeneratedDocuments");

                    b.Navigation("Logo");

                    b.Navigation("MailLogs");
                });

            modelBuilder.Entity("Kalon.Back.Models.User", b =>
                {
                    b.Navigation("Organization");
                });
#pragma warning restore 612, 618
        }
    }
}
